# Generated by Django 4.2 on 2023-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wishlist_Item",
            new_name="WishlistItem",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                related_name="wishes",
                through="wishlist.WishlistItem",
                to="product.product",
            ),
        ),
    ]
