# Generated by Django 4.2 on 2023-05-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.CharField(default="", max_length=200),
        ),
    ]
