# Generated by Django 4.2 on 2023-05-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
