# Generated by Django 4.2 on 2023-05-09 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopping_cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="quntity",
            new_name="quantity",
        ),
    ]
