# Generated by Django 4.2 on 2023-05-10 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_category_id"),
        ("shopping_cart", "0002_rename_quntity_cartitem_quantity"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CartItem",
            new_name="Cart_Item",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
