# Generated by Django 4.2 on 2023-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.TextField(null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=20, null=True, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=50, null=True, verbose_name="Country"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(max_length=20, null=True, verbose_name="Phone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="postalCode",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Postal Code "
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(max_length=50, null=True, verbose_name="State"),
        ),
    ]
