# Generated by Django 4.2 on 2023-05-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
