# Generated by Django 4.2 on 2023-05-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash on delivery"), ("online", "Online payment")],
                default="cash",
                max_length=10,
            ),
        ),
    ]
