# Generated by Django 4.2 on 2023-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
