# Generated by Django 4.2 on 2023-05-20 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_remove_order_payment_status_order_paid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
    ]
