# Generated by Django 4.2 on 2023-05-24 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
    ]
